# Generated by Django 5.0.6 on 2024-07-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormWizard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=50)),
            ],
        ),
    ]
