# Generated by Django 5.0.6 on 2024-07-11 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_wizard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formwizard",
            name="address",
        ),
        migrations.RemoveField(
            model_name="formwizard",
            name="city",
        ),
        migrations.RemoveField(
            model_name="formwizard",
            name="country",
        ),
        migrations.RemoveField(
            model_name="formwizard",
            name="state",
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=50)),
                (
                    "form_wizard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="form_wizard.formwizard",
                    ),
                ),
            ],
        ),
    ]
